# ruff: noqa: D100, RUF012
# Generated by Django 6.0.5 on 2026-09-02 13:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import django_plugin_field_day


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
            ],
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('kind', models.CharField(max_length=20)),
                (
                    'country',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subdivisions',
                        to='django_plugin_field_day.country',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'recipient',
                    models.CharField(
                        max_length=35,
                        validators=[
                            django.core.validators.RegexValidator(
                                '^[\\x20-\\x7e\\xa0-\\xff]*$',
                                'Only Latin-1 printable characters fit on a shipping label.',
                            )
                        ],
                    ),
                ),
                (
                    'street1',
                    models.CharField(
                        max_length=35,
                        validators=[
                            django.core.validators.RegexValidator(
                                '^[\\x20-\\x7e\\xa0-\\xff]*$',
                                'Only Latin-1 printable characters fit on a shipping label.',
                            )
                        ],
                    ),
                ),
                (
                    'street2',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=35,
                        validators=[
                            django.core.validators.RegexValidator(
                                '^[\\x20-\\x7e\\xa0-\\xff]*$',
                                'Only Latin-1 printable characters fit on a shipping label.',
                            )
                        ],
                    ),
                ),
                (
                    'street3',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=35,
                        validators=[
                            django.core.validators.RegexValidator(
                                '^[\\x20-\\x7e\\xa0-\\xff]*$',
                                'Only Latin-1 printable characters fit on a shipping label.',
                            )
                        ],
                    ),
                ),
                (
                    'city',
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                '^[\\x20-\\x7e\\xa0-\\xff]*$',
                                'Only Latin-1 printable characters fit on a shipping label.',
                            )
                        ],
                    ),
                ),
                ('postal_code', models.CharField(max_length=10)),
                (
                    'country',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='django_plugin_field_day.country',
                    ),
                ),
                (
                    'subdivision',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='django_plugin_field_day.subdivision',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('recipient__regex', '[\\n\\r\\t]'), _negated=True),
                            models.Q(('street1__regex', '[\\n\\r\\t]'), _negated=True),
                            models.Q(('street2__regex', '[\\n\\r\\t]'), _negated=True),
                            models.Q(('street3__regex', '[\\n\\r\\t]'), _negated=True),
                            models.Q(('city__regex', '[\\n\\r\\t]'), _negated=True),
                        ),
                        name='address_no_control_characters',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ('recipient__regex', '\\S'),
                            ('street1__regex', '\\S'),
                            ('city__regex', '\\S'),
                        ),
                        name='address_required_lines_present',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('street2', ''), ('street2__regex', '\\S'), _connector='OR'),
                            models.Q(('street3', ''), ('street3__regex', '\\S'), _connector='OR'),
                        ),
                        name='address_optional_lines_not_blank',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('street2', ''), _negated=True),
                            ('street3', ''),
                            _connector='OR',
                        ),
                        name='address_street_lines_no_gap',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ('subdivision__isnull', True),
                            ('country', django_plugin_field_day.Left('subdivision', 2)),
                            _connector='OR',
                        ),
                        name='address_subdivision_in_country',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ('subdivision__isnull', False),
                            models.Q(('country__in', ('US', 'CN')), _negated=True),
                            _connector='OR',
                        ),
                        name='address_subdivision_required_by_country',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ('country', 'US'), ('postal_code__regex', '^\\d{5}(-\\d{4})?$')
                            ),
                            models.Q(
                                ('country', 'GB'),
                                (
                                    'postal_code__regex',
                                    '^[A-Za-z]{1,2}\\d[A-Za-z\\d]? ?\\d[A-Za-z]{2}$',
                                ),
                            ),
                            models.Q(('country', 'CN'), ('postal_code__regex', '^\\d{6}$')),
                            _connector='OR',
                        ),
                        name='address_postal_code_matches_country',
                    ),
                ],
            },
        ),
    ]
