"""ISO 3166-1 alpha-2 countries from Chromium libaddressinput; see scripts/fetch_countries.py."""

COUNTRIES = (
    ('AC', 'ASCENSION ISLAND', None),
    ('AD', 'ANDORRA', None),
    ('AE', 'UNITED ARAB EMIRATES', None),
    ('AF', 'AFGHANISTAN', None),
    ('AG', 'ANTIGUA AND BARBUDA', None),
    ('AI', 'ANGUILLA', None),
    ('AL', 'ALBANIA', None),
    ('AM', 'ARMENIA', None),
    ('AO', 'ANGOLA', None),
    ('AQ', 'ANTARCTICA', None),
    ('AR', 'ARGENTINA', None),
    ('AS', 'AMERICAN SAMOA', 'US'),
    ('AT', 'AUSTRIA', None),
    ('AU', 'AUSTRALIA', None),
    ('AW', 'ARUBA', None),
    ('AX', 'FINLAND', None),
    ('AZ', 'AZERBAIJAN', None),
    ('BA', 'BOSNIA AND HERZEGOVINA', None),
    ('BB', 'BARBADOS', None),
    ('BD', 'BANGLADESH', None),
    ('BE', 'BELGIUM', None),
    ('BF', 'BURKINA FASO', None),
    ('BG', 'BULGARIA (REP.)', None),
    ('BH', 'BAHRAIN', None),
    ('BI', 'BURUNDI', None),
    ('BJ', 'BENIN', None),
    ('BL', 'SAINT BARTHELEMY', None),
    ('BM', 'BERMUDA', None),
    ('BN', 'BRUNEI DARUSSALAM', None),
    ('BO', 'BOLIVIA', None),
    ('BQ', 'BONAIRE, SINT EUSTATIUS, AND SABA', None),
    ('BR', 'BRAZIL', None),
    ('BS', 'BAHAMAS', None),
    ('BT', 'BHUTAN', None),
    ('BV', 'BOUVET ISLAND', None),
    ('BW', 'BOTSWANA', None),
    ('BY', 'BELARUS', None),
    ('BZ', 'BELIZE', None),
    ('CA', 'CANADA', None),
    ('CC', 'COCOS (KEELING) ISLANDS', None),
    ('CD', 'CONGO (DEM. REP.)', None),
    ('CF', 'CENTRAL AFRICAN REPUBLIC', None),
    ('CG', 'CONGO (REP.)', None),
    ('CH', 'SWITZERLAND', None),
    ('CI', "COTE D'IVOIRE", None),
    ('CK', 'COOK ISLANDS', None),
    ('CL', 'CHILE', None),
    ('CM', 'CAMEROON', None),
    ('CN', 'CHINA', None),
    ('CO', 'COLOMBIA', None),
    ('CR', 'COSTA RICA', None),
    ('CU', 'CUBA', None),
    ('CV', 'CAPE VERDE', None),
    ('CW', 'CURACAO', None),
    ('CX', 'CHRISTMAS ISLAND', None),
    ('CY', 'CYPRUS', None),
    ('CZ', 'CZECH REP.', None),
    ('DE', 'GERMANY', None),
    ('DJ', 'DJIBOUTI', None),
    ('DK', 'DENMARK', None),
    ('DM', 'DOMINICA', None),
    ('DO', 'DOMINICAN REP.', None),
    ('DZ', 'ALGERIA', None),
    ('EC', 'ECUADOR', None),
    ('EE', 'ESTONIA', None),
    ('EG', 'EGYPT', None),
    ('EH', 'WESTERN SAHARA', None),
    ('ER', 'ERITREA', None),
    ('ES', 'SPAIN', None),
    ('ET', 'ETHIOPIA', None),
    ('FI', 'FINLAND', None),
    ('FJ', 'FIJI', None),
    ('FK', 'FALKLAND ISLANDS (MALVINAS)', None),
    ('FM', 'MICRONESIA (Federated State of)', None),
    ('FO', 'FAROE ISLANDS', None),
    ('FR', 'FRANCE', None),
    ('GA', 'GABON', None),
    ('GB', 'UNITED KINGDOM', None),
    ('GD', 'GRENADA (WEST INDIES)', None),
    ('GE', 'GEORGIA', None),
    ('GF', 'FRENCH GUIANA', None),
    ('GG', 'CHANNEL ISLANDS', None),
    ('GH', 'GHANA', None),
    ('GI', 'GIBRALTAR', None),
    ('GL', 'GREENLAND', None),
    ('GM', 'GAMBIA', None),
    ('GN', 'GUINEA', None),
    ('GP', 'GUADELOUPE', None),
    ('GQ', 'EQUATORIAL GUINEA', None),
    ('GR', 'GREECE', None),
    ('GS', 'SOUTH GEORGIA', None),
    ('GT', 'GUATEMALA', None),
    ('GU', 'GUAM', 'US'),
    ('GW', 'GUINEA-BISSAU', None),
    ('GY', 'GUYANA', None),
    ('HK', 'HONG KONG', None),
    ('HM', 'HEARD AND MCDONALD ISLANDS', None),
    ('HN', 'HONDURAS', None),
    ('HR', 'CROATIA', None),
    ('HT', 'HAITI', None),
    ('HU', 'HUNGARY (Rep.)', None),
    ('ID', 'INDONESIA', None),
    ('IE', 'IRELAND', None),
    ('IL', 'ISRAEL', None),
    ('IM', 'ISLE OF MAN', None),
    ('IN', 'INDIA', None),
    ('IO', 'BRITISH INDIAN OCEAN TERRITORY', None),
    ('IQ', 'IRAQ', None),
    ('IR', 'IRAN', None),
    ('IS', 'ICELAND', None),
    ('IT', 'ITALY', None),
    ('JE', 'CHANNEL ISLANDS', None),
    ('JM', 'JAMAICA', None),
    ('JO', 'JORDAN', None),
    ('JP', 'JAPAN', None),
    ('KE', 'KENYA', None),
    ('KG', 'KYRGYZSTAN', None),
    ('KH', 'CAMBODIA', None),
    ('KI', 'KIRIBATI', None),
    ('KM', 'COMOROS', None),
    ('KN', 'SAINT KITTS AND NEVIS', None),
    ('KP', 'NORTH KOREA', None),
    ('KR', 'SOUTH KOREA', None),
    ('KW', 'KUWAIT', None),
    ('KY', 'CAYMAN ISLANDS', None),
    ('KZ', 'KAZAKHSTAN', None),
    ('LA', "LAO (PEOPLE'S DEM. REP.)", None),
    ('LB', 'LEBANON', None),
    ('LC', 'SAINT LUCIA', None),
    ('LI', 'LIECHTENSTEIN', None),
    ('LK', 'SRI LANKA', None),
    ('LR', 'LIBERIA', None),
    ('LS', 'LESOTHO', None),
    ('LT', 'LITHUANIA', None),
    ('LU', 'LUXEMBOURG', None),
    ('LV', 'LATVIA', None),
    ('LY', 'LIBYA', None),
    ('MA', 'MOROCCO', None),
    ('MC', 'MONACO', None),
    ('MD', 'Rep. MOLDOVA', None),
    ('ME', 'MONTENEGRO', None),
    ('MF', 'SAINT MARTIN', None),
    ('MG', 'MADAGASCAR', None),
    ('MH', 'MARSHALL ISLANDS', None),
    ('MK', 'MACEDONIA', None),
    ('ML', 'MALI', None),
    ('MM', 'MYANMAR', None),
    ('MN', 'MONGOLIA', None),
    ('MO', 'MACAO', None),
    ('MP', 'NORTHERN MARIANA ISLANDS', 'US'),
    ('MQ', 'MARTINIQUE', None),
    ('MR', 'MAURITANIA', None),
    ('MS', 'MONTSERRAT', None),
    ('MT', 'MALTA', None),
    ('MU', 'MAURITIUS', None),
    ('MV', 'MALDIVES', None),
    ('MW', 'MALAWI', None),
    ('MX', 'MEXICO', None),
    ('MY', 'MALAYSIA', None),
    ('MZ', 'MOZAMBIQUE', None),
    ('NA', 'NAMIBIA', None),
    ('NC', 'NEW CALEDONIA', None),
    ('NE', 'NIGER', None),
    ('NF', 'NORFOLK ISLAND', None),
    ('NG', 'NIGERIA', None),
    ('NI', 'NICARAGUA', None),
    ('NL', 'NETHERLANDS', None),
    ('NO', 'NORWAY', None),
    ('NP', 'NEPAL', None),
    ('NR', 'NAURU CENTRAL PACIFIC', None),
    ('NU', 'NIUE', None),
    ('NZ', 'NEW ZEALAND', None),
    ('OM', 'OMAN', None),
    ('PA', 'PANAMA (REP.)', None),
    ('PE', 'PERU', None),
    ('PF', 'FRENCH POLYNESIA', None),
    ('PG', 'PAPUA NEW GUINEA', None),
    ('PH', 'PHILIPPINES', None),
    ('PK', 'PAKISTAN', None),
    ('PL', 'POLAND', None),
    ('PM', 'ST. PIERRE AND MIQUELON', None),
    ('PN', 'PITCAIRN', None),
    ('PR', 'PUERTO RICO', 'US'),
    ('PS', 'PALESTINIAN TERRITORY', None),
    ('PT', 'PORTUGAL', None),
    ('PW', 'PALAU', None),
    ('PY', 'PARAGUAY', None),
    ('QA', 'QATAR', None),
    ('RE', 'REUNION', None),
    ('RO', 'ROMANIA', None),
    ('RS', 'REPUBLIC OF SERBIA', None),
    ('RU', 'RUSSIAN FEDERATION', None),
    ('RW', 'RWANDA', None),
    ('SA', 'SAUDI ARABIA', None),
    ('SB', 'SOLOMON ISLANDS', None),
    ('SC', 'SEYCHELLES', None),
    ('SD', 'SUDAN', None),
    ('SE', 'SWEDEN', None),
    ('SG', 'REP. OF SINGAPORE', None),
    ('SH', 'SAINT HELENA', None),
    ('SI', 'SLOVENIA', None),
    ('SJ', 'SVALBARD AND JAN MAYEN ISLANDS', None),
    ('SK', 'SLOVAKIA', None),
    ('SL', 'SIERRA LEONE', None),
    ('SM', 'SAN MARINO', None),
    ('SN', 'SENEGAL', None),
    ('SO', 'SOMALIA', None),
    ('SR', 'SURINAME', None),
    ('SS', 'SOUTH SUDAN', None),
    ('ST', 'SAO TOME AND PRINCIPE', None),
    ('SV', 'EL SALVADOR', None),
    ('SX', 'SINT MAARTEN', None),
    ('SY', 'SYRIA', None),
    ('SZ', 'SWAZILAND', None),
    ('TA', 'TRISTAN DA CUNHA', None),
    ('TC', 'TURKS AND CAICOS ISLANDS', None),
    ('TD', 'CHAD', None),
    ('TF', 'FRENCH SOUTHERN TERRITORIES', None),
    ('TG', 'TOGO', None),
    ('TH', 'THAILAND', None),
    ('TJ', 'TAJIKISTAN', None),
    ('TK', 'TOKELAU', None),
    ('TL', 'TIMOR-LESTE', None),
    ('TM', 'TURKMENISTAN', None),
    ('TN', 'TUNISIA', None),
    ('TO', 'TONGA', None),
    ('TR', 'TURKEY', None),
    ('TT', 'TRINIDAD AND TOBAGO', None),
    ('TV', 'TUVALU', None),
    ('TW', 'TAIWAN', None),
    ('TZ', 'TANZANIA (UNITED REP.)', None),
    ('UA', 'UKRAINE', None),
    ('UG', 'UGANDA', None),
    ('UM', 'UNITED STATES MINOR OUTLYING ISLANDS', 'US'),
    ('US', 'UNITED STATES', None),
    ('UY', 'URUGUAY', None),
    ('UZ', 'UZBEKISTAN', None),
    ('VA', 'VATICAN', None),
    ('VC', 'SAINT VINCENT AND THE GRENADINES (ANTILLES)', None),
    ('VE', 'VENEZUELA', None),
    ('VG', 'VIRGIN ISLANDS (BRITISH)', None),
    ('VI', 'VIRGIN ISLANDS (U.S.)', 'US'),
    ('VN', 'VIET NAM', None),
    ('VU', 'VANUATU', None),
    ('WF', 'WALLIS AND FUTUNA ISLANDS', None),
    ('WS', 'SAMOA', None),
    ('XK', 'KOSOVO', None),
    ('YE', 'YEMEN', None),
    ('YT', 'MAYOTTE', None),
    ('ZA', 'SOUTH AFRICA', None),
    ('ZM', 'ZAMBIA', None),
    ('ZW', 'ZIMBABWE', None),
)
